React Calculator
GraceOyiza/react-calculator pull request #2
Opened 2021-07-16 18:40 UTC by GraceOyiza

- Add components directory.
- Add Display, App, Button and ButtonPanel components.

2021-07-16 20:35 UTC, bellom requested changes
## Hi @GraceOyiza  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-07-16 20:35 UTC, bellom commented on .eslintrc.json
> +    "linebreak-style": 0
Oops, we have some little changes in this file, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json)
Kindly make use of the files provided by Microverse without editing them. However, if you're getting a linter error, do well to check the project requirement page under **TIP**

2021-07-16 20:35 UTC, bellom commented on src/components/App.js
> +          </ButtonPannel>
Good job so far 👍 ....

But we need to move this mapping implementation inside the `buttonPanel.js`
![image](https://user-images.githubusercontent.com/31897434/126005548-6e5b9231-dfb1-4f98-a103-48ad37e3800e.png)


![image](https://user-images.githubusercontent.com/31897434/126005577-12ea9b50-8269-4930-8fe9-5ffb3d83a94b.png)

2021-07-16 20:41 UTC, bellom commented on src/components/ButtonPanel.js
> +  return <div className="button_panel">{children}</div>;
Hint:

Microverse encourage DRY-(Don't Repeat Yourself) code, In your case; you repeated the `Button` component multiple times.

You can use [objects.key](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)  and `map` to loop through the objects. `objects.keys` for the outer loop and `map` for the inner loop.

Example; 
```
const GroupButtons = {
  Group 1: ['AC', '+/-', '%', '÷'],
  Group 2: ['7', '8', '9', 'X'],
   ............
}
```

2021-07-20 10:33 UTC, GraceOyiza commented
- Fix microverse lint errors without changing them.
- Move mapping implementation into ButtonPanel.js.
- Implement the DRY Principle

2021-07-20 10:59 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED👍️👍️👍️👍️**

Hello @GraceOyiza 

Great work making the required changes👏️👏️👏️

You can merge👍️👍️

Happy coding💻️💻️

2021-07-29 13:01 UTC, merged