Testing code
GraceOyiza/react-calculator pull request #6
Opened 2021-08-02 21:38 UTC by GraceOyiza

- Add test folder
- Tested component.js
- Tested for logic.js

2021-08-02 23:39 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @GraceOyiza, I am Elias, your reviewer for this PR

Well done so far with your project!

The current tests that you have are passing as expected and you didn't forget about negative tests, good job!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] All functionalities are tested using [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/), `@testing-library/react`, see the [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/testing/useReactTestingLibrary.png) from [Pathwright](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106580952/).
(Currently, you are using react-test-renderer which is not allowed for this project so please migrate to the other one mentioned in the requirements by Microverse)
- [ ] All functions in calculate.js file are covered with unit tests (currently, I can only see that you are testing the multiplication and plus functionalities, you are missing the rest: %, +/-, ".", AC, and the division by 0).
- [ ] There are snapshot tests that are checking if the main components, at least Home, Calculator, and Quote, from Math Magicians mockups are displayed (From what I can see you are missing to test the Home component because the App.test.js is testing the Quote one, please add it and rename your test to quote and home/app to avoid confusion for the next CR).
- [ ] Please create one expect per test, divide the tests with multiple expects in multiple tests because this makes it easier to debug or find which test is failing.

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-02 23:39 UTC, e71az commented on src/test/logic/operate.test.js
> +    expect(answer.toString()).toEqual('9');
- [ ] Please divide this and any other test that has many expects inside into multiple tests with only 1 expect inside each one.

2021-08-02 23:39 UTC, e71az commented on src/test/pages/App.test.js
> +import React from 'react';
- [ ] Please change the name of this file to Quote.test.js to avoid confusions

2021-08-02 23:39 UTC, e71az commented on src/test/logic/calculate.test.js
> +import Calculate from '../../logic/calculate';
- [ ] In this file please add tests for all your calculate functionalities like: %, +/-, ".", AC, and the division by 0.

2021-08-02 23:39 UTC, e71az commented on src/test/components/Button.test.js
> +import render from 'react-test-renderer';
- [ ] Please avoid using react-test-renderer in this project and instead use the one mentioned in the requirements which is: @testing-library/react to learn a new testing tool :)

2021-08-05 13:40 UTC, GraceOyiza commented
-  All functionalities were tested using React Testing Library.
- All required changes fixed

2021-08-05 15:00 UTC, george-shammar requested changes
Hi @GraceOyiza , 

Good job so far! :+1:  And thank you for implementing some of the required changes. 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-08-06 12:08 UTC, GraceOyiza commented
- All required changes fixed.

2021-08-06 12:27 UTC, george-shammar approved these changes
Hi @GraceOyiza ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------

2021-08-06 15:58 UTC, merged